{
 "title": "PromHouse API",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Read requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(promhouse_api_reads_started[1m])",
     "legendFormat": "Rate"
    },
    {
     "expr": "sum(promhouse_api_reads_started) - sum(promhouse_api_reads_count)",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Write requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "rate(promhouse_api_writes_started[1m])",
     "legendFormat": "Rate"
    },
    {
     "expr": "sum(promhouse_api_writes_started) - sum(promhouse_api_writes_count)",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Read errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "increase(promhouse_api_reads_count{type!=\"ok\"}[1m])",
     "legendFormat": "Rate {{ type }}"
    }
   ]
  },
  {
   "title": "Write errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "wpm" }
   ],
   "targets": [
    {
     "expr": "increase(promhouse_api_writes_count{type!=\"ok\"}[1m])",
     "legendFormat": "Rate {{ type }}"
    }
   ]
  },
  {
   "title": "Reads duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "promhouse_api_reads{type=\"ok\"}",
     "legendFormat": "{{ quantile }}φ"
    }
   ]
  },
  {
   "title": "Writes duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "promhouse_api_writes{type=\"ok\"}",
     "legendFormat": "{{ quantile }}φ"
    }
   ]
  },
  {
   "title": "Samples written",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "rate(promhouse_api_written_samples[1m])",
     "legendFormat": "Rate"
    }
   ]
  }
 ]
}