{
 "title": "ClickHouse",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Table bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "clickhouse_table_parts_bytes", "legendFormat": "{{ table }}" }
   ]
  },
  {
   "title": "Table rows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "clickhouse_table_parts_rows", "legendFormat": "{{ table }}" }
   ]
  },
  {
   "title": "Table parts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "clickhouse_table_parts_count", "legendFormat": "{{ table }}" }
   ]
  },
  {
   "title": "Samples",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "clickhouse_table_parts_bytes{table=\"samples\"}",
     "legendFormat": "Bytes"
    },
    {
     "expr": "clickhouse_table_parts_rows{table=\"samples\"} * (8+8+8)",
     "legendFormat": "Virtual bytes"
    }
   ]
  },
  {
   "title": "Compression ratio",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "clickhouse_table_parts_bytes{table=\"samples\"} / clickhouse_table_parts_rows{table=\"samples\"} * (8+8+8)"
    }
   ]
  },
  {
   "title": "Inserts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_insert_query_total[1m])",
     "legendFormat": "Queries"
    },
    {
     "expr": "rate(clickhouse_inserted_rows_total[1m])",
     "legendFormat": "Rows"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "clickhouse_query", "legendFormat": "Current" }
   ]
  }
 ]
}